/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.awt.Graphics;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.DefaultListModel;
import javax.swing.JList;

/**
 *
 * @author RAndom MC
 */
public class GUI extends javax.swing.JFrame {
    private int x1, y1, x2, y2;


    /**
     * Creates new form GUI
     */
    public GUI() {
        this.mainComponents = new MainComponents();
        initComponents();  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        upload = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        givenRefName = new javax.swing.JTextField();
        refDialCancel = new javax.swing.JButton();
        refDialOK = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        writeJSONconfirm = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        writeJSONBtn = new javax.swing.JButton();
        cancelWriteBtn = new javax.swing.JButton();
        JSONPathBtn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        upperNavi = new javax.swing.JPanel();
        openProject = new javax.swing.JButton();
        newProject = new javax.swing.JButton();
        save = new javax.swing.JButton();
        picScrField = new javax.swing.JTextField();
        uploadBtn = new javax.swing.JButton();
        mainTitle = new javax.swing.JLabel();
        settigns = new javax.swing.JButton();
        leftNavi = new javax.swing.JPanel();
        filesPanel = new javax.swing.JScrollPane();
        availableFilesModel = new DefaultListModel();
        availableFilesListener = new MouseAdapter(){
            @Override
            public void mouseClicked(MouseEvent e) {
                availableFilesEvent(e);
            }
        };
        availableFiles = new JList(availableFilesModel);
        availableFiles.addMouseListener(availableFilesListener);
        projectsPanel = new javax.swing.JScrollPane();
        availableProjectsModel = new DefaultListModel();
        availableProjects = new javax.swing.JList(availableProjectsModel);
        availableProjectsListener = new MouseAdapter(){
            @Override
            public void mouseClicked(MouseEvent e){
                availableProjectsEvent(e);
            }
        };
        availableProjects.addMouseListener(availableProjectsListener);
        projectsLabel = new javax.swing.JLabel();
        filesLabel = new javax.swing.JLabel();
        writeJSONMainBtn = new javax.swing.JButton();
        drawTool = new javax.swing.JToggleButton();
        deletePointTool = new javax.swing.JToggleButton();
        drawArea = new DrawArea(null,this.mainComponents);//custom luokka
        NewProjectNameLabel1 = new javax.swing.JLabel();
        newProjectNameField = new javax.swing.JTextField();
        giveProjectNameCancel = new javax.swing.JButton();
        giveProjectNameOK = new javax.swing.JButton();
        giveProjectName = new javax.swing.JDialog();
        newProjectNameTitle = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();

        upload.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        upload.setAlwaysOnTop(true);
        upload.setLocation(new java.awt.Point(340, 150));
        upload.setMinimumSize(new java.awt.Dimension(400, 225));
        upload.setPreferredSize(new java.awt.Dimension(400, 225));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Please give a JSON reference name for this file");

        givenRefName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        givenRefName.setText("Shape1");

        refDialCancel.setText("Cancel");
        refDialCancel.setToolTipText("");
        refDialCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refDialCancelActionPerformed(evt);
            }
        });

        refDialOK.setText("OK");
        refDialOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refDialOKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout uploadLayout = new javax.swing.GroupLayout(upload.getContentPane());
        upload.getContentPane().setLayout(uploadLayout);
        uploadLayout.setHorizontalGroup(
            uploadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(uploadLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(uploadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(uploadLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(givenRefName, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(uploadLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                        .addContainerGap())))
            .addComponent(jSeparator2)
            .addGroup(uploadLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(refDialOK, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(refDialCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        uploadLayout.setVerticalGroup(
            uploadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(uploadLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(givenRefName, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(uploadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(refDialCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(refDialOK, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        writeJSONconfirm.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        writeJSONconfirm.setMinimumSize(new java.awt.Dimension(400, 225));
        writeJSONconfirm.setPreferredSize(new java.awt.Dimension(400, 225));
        writeJSONconfirm.setLocation(new java.awt.Point(235, 110));
        
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Confirm file name...");
        jLabel2.setToolTipText("");
        jLabel2.setFocusable(false);
        jLabel2.setInheritsPopupMenu(false);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Name:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Path:");

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField1.setText("physics.json");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField2.setText("C://CollisionDrawer/default/");

        writeJSONBtn.setText("Write");
        writeJSONBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                writeJSONBtnActionPerformed(evt);
            }
        });
        
        
        cancelWriteBtn.setText("Cancel");
        cancelWriteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelWriteBtnActionPerformed(evt);
            }
        });

        JSONPathBtn.setText("Browse");

        javax.swing.GroupLayout writeJSONconfirmLayout = new javax.swing.GroupLayout(writeJSONconfirm.getContentPane());
        writeJSONconfirm.getContentPane().setLayout(writeJSONconfirmLayout);
        writeJSONconfirmLayout.setHorizontalGroup(
            writeJSONconfirmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, writeJSONconfirmLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83))
            .addGroup(writeJSONconfirmLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(writeJSONconfirmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(writeJSONconfirmLayout.createSequentialGroup()
                        .addGroup(writeJSONconfirmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(writeJSONconfirmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                            .addComponent(jTextField1)))
                    .addGroup(writeJSONconfirmLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(JSONPathBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(writeJSONBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cancelWriteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(39, Short.MAX_VALUE))
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        writeJSONconfirmLayout.setVerticalGroup(
            writeJSONconfirmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(writeJSONconfirmLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(writeJSONconfirmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(writeJSONconfirmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(writeJSONconfirmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cancelWriteBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(writeJSONconfirmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(JSONPathBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(writeJSONBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        
        giveProjectName.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        giveProjectName.setMinimumSize(new java.awt.Dimension(400, 225));
        giveProjectName.setPreferredSize(new java.awt.Dimension(400, 225));
        giveProjectName.setLocation(new java.awt.Point(235, 110));
        newProjectNameTitle.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        newProjectNameTitle.setText("Please give a name for new project");

        NewProjectNameLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        NewProjectNameLabel1.setText("New name:");

        giveProjectNameCancel.setText("Cancel");
        giveProjectNameCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                giveProjectNameCancelActionPerformed(evt);
            }
        });

        giveProjectNameOK.setText("OK");
        giveProjectNameOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                giveProjectNameOKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout giveProjectNameLayout = new javax.swing.GroupLayout(giveProjectName.getContentPane());
        giveProjectName.getContentPane().setLayout(giveProjectNameLayout);
        giveProjectNameLayout.setHorizontalGroup(
            giveProjectNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(giveProjectNameLayout.createSequentialGroup()
                .addGroup(giveProjectNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(giveProjectNameLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(newProjectNameTitle))
                    .addGroup(giveProjectNameLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(giveProjectNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NewProjectNameLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(giveProjectNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, giveProjectNameLayout.createSequentialGroup()
                                    .addComponent(giveProjectNameOK, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(giveProjectNameCancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(newProjectNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        giveProjectNameLayout.setVerticalGroup(
            giveProjectNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(giveProjectNameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(newProjectNameTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NewProjectNameLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newProjectNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(giveProjectNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(giveProjectNameCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(giveProjectNameOK, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setForeground(java.awt.Color.white);
        setPreferredSize(new java.awt.Dimension(1200, 800));
        setResizable(false);

        upperNavi.setBackground(new java.awt.Color(235, 235, 235));
        upperNavi.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 1, new java.awt.Color(0, 0, 0)));

        openProject.setText("Open Project");
        openProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openProjectActionPerformed(evt);
            }
        });

        newProject.setText("New Project");
        newProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newProjectActionPerformed(evt);
            }
        });

        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        picScrField.setText("...");
        picScrField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                picScrFieldMouseClicked(evt);
            }
        });

        uploadBtn.setText("Choose...");
        uploadBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadFileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout upperNaviLayout = new javax.swing.GroupLayout(upperNavi);
        upperNavi.setLayout(upperNaviLayout);
        upperNaviLayout.setHorizontalGroup(
            upperNaviLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(upperNaviLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(save, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(openProject)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newProject)
                .addGap(22, 22, 22)
                .addComponent(picScrField, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(uploadBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                .addContainerGap())
        );
        upperNaviLayout.setVerticalGroup(
            upperNaviLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(upperNaviLayout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addGroup(upperNaviLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uploadBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(picScrField, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newProject, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(openProject, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(save, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );

        mainTitle.setBackground(new java.awt.Color(255, 255, 255));
        mainTitle.setFont(new java.awt.Font("Xpress SF", 0, 48)); // NOI18N
        mainTitle.setText("CollisionDrawer");
        mainTitle.setOpaque(true);

        settigns.setBackground(new java.awt.Color(255, 255, 255));
        settigns.setIcon(new javax.swing.ImageIcon("C:\\Users\\RAndom MC\\Documents\\AlbumArtSmall.jpg")); // NOI18N
        settigns.setToolTipText("");
        settigns.setBorder(null);
        settigns.setBorderPainted(false);
        settigns.setContentAreaFilled(false);

        /*javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(upperNavi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(55, 55, 55)
                .addComponent(mainTitle)
                .addGap(50, 50, 50)
                .addComponent(settigns, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(mainTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(upperNavi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(settigns)
                .addContainerGap(714, Short.MAX_VALUE))
        );*/
        
        leftNavi.setBackground(new java.awt.Color(250, 250, 250));
        leftNavi.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        leftNavi.setToolTipText("");

        availableFiles.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        /*availableFiles.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });*/
        //availableFiles.setModel(new javax.swing.DefaultListModel<>());
                
        filesPanel.setViewportView(availableFiles);

        availableProjects.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        /*availableProjects.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });*/
        projectsPanel.setViewportView(availableProjects);

        projectsLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        projectsLabel.setText("Projects");

        filesLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        filesLabel.setText("Files");

        writeJSONMainBtn.setText("Make JSON");
        writeJSONMainBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                writeJSONMainBtnActionPerformed(evt);
            }
        });

        drawTool.setText("Draw");
        drawTool.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drawToolActionPerformed(evt);
            }
        });

        deletePointTool.setText("Delete");
        deletePointTool.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletePointToolActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout leftNaviLayout = new javax.swing.GroupLayout(leftNavi);
        leftNavi.setLayout(leftNaviLayout);
        leftNaviLayout.setHorizontalGroup(
            leftNaviLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftNaviLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(leftNaviLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(leftNaviLayout.createSequentialGroup()
                        .addComponent(writeJSONMainBtn)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(leftNaviLayout.createSequentialGroup()
                        .addGroup(leftNaviLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(filesPanel)
                            .addComponent(projectsPanel)
                            .addGroup(leftNaviLayout.createSequentialGroup()
                                .addGroup(leftNaviLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(filesLabel)
                                    .addGroup(leftNaviLayout.createSequentialGroup()
                                        .addComponent(drawTool, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(deletePointTool)))
                                .addGap(0, 62, Short.MAX_VALUE))
                            .addGroup(leftNaviLayout.createSequentialGroup()
                                .addComponent(projectsLabel)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        leftNaviLayout.setVerticalGroup(
            leftNaviLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, leftNaviLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(leftNaviLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(drawTool)
                .addComponent(deletePointTool))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(writeJSONMainBtn)
                .addGap(18, 18, 18)
                .addComponent(projectsLabel)
                .addGap(18, 18, 18)
                .addComponent(projectsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(filesLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(filesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        drawArea.setBackground(new java.awt.Color(250, 250, 250));
        drawArea.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        /*javax.swing.GroupLayout drawAreaLayout = new javax.swing.GroupLayout(drawArea);
        drawArea.setLayout(drawAreaLayout);
        drawAreaLayout.setHorizontalGroup(
            drawAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 944, Short.MAX_VALUE)
        );
        drawAreaLayout.setVerticalGroup(
            drawAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );*/
        drawArea.setLayout(null);
        //tässä ongelma
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()  
                .addContainerGap()
                .addComponent(leftNavi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(drawArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
                //
            .addGroup(layout.createSequentialGroup()
                .addComponent(upperNavi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(55, 55, 55)
                .addComponent(mainTitle)
                .addGap(50, 50, 50)
                .addComponent(settigns, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(drawArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(leftNavi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(mainTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(upperNavi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(settigns)
                .addContainerGap(714, Short.MAX_VALUE))
        );
        
        pack();
    }// </editor-fold>                        
    //tässä on listaeventit
    private void availableFilesEvent(MouseEvent e){
        mainComponents.changeFile(availableFiles.getSelectedIndex(),drawArea);//Uudelleen piirtäminen tehdään mainComponentin ja DrawArean yhteistyönä jotta GUIn koodista ei tulisi clusterfuckkia
        updateRenamer();
        repaint();
    };
     private void availableProjectsEvent(MouseEvent e){
        mainComponents.changeProject(availableProjects.getSelectedIndex(),drawArea,availableFilesModel);//sama kuin edellä
        this.availableFiles.setSelectedIndex(0);
        updateRenamer();
        repaint();
    };
    //tässä loput eventit
    private void uploadFileActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
        if(availableProjectsModel.getSize() != 0){
            mainComponents.newFile(drawArea, availableFilesModel, availableFiles);
            updateRenamer();
            repaint();
        }
        //alla on esimerkki 2ulotteista taulukosta 
        //int[][] point = new int[1][2];
        //point[0][0]= 30;
        //point[0][1] = 20;
        //file.setPoints(point);
        //System.out.println(file.getPoints().get(0));
        //int test = file.removePoint(29, 21);
        //System.out.println(file.getPoints().size());
    }
    // tämä metodi toteuttaa tapahtuman käsittelyn kun painetaan draw -painiketta.
    private void drawToolActionPerformed(java.awt.event.ActionEvent evt) {                                            
        this.drawArea.addMouseListener(new MousePressedTracker());
        //this.drawArea.setLayout(new GridLayout(0, 1));
    }
    
    private void deletePointToolActionPerformed(java.awt.event.ActionEvent evt) {
        
    }
    
    class MousePressedTracker extends MouseAdapter {
        @Override
        public void mousePressed(MouseEvent e){
            x2 = e.getX();
            y2 = e.getY();
            Graphics g = drawArea.getGraphics();
            mainComponents.setCoord(x2, y2, g, drawArea);
            repaint();
        }
    }
                                               
    private void openProjectActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void newProjectActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        giveProjectName.setVisible(true);
    } 

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
    }                                    

    private void refDialCancelActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
        upload.dispose();
    }                                             

    private void refDialOKActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        mainComponents.renameFile(this.givenRefName.getText(), availableFilesModel);
        updateRenamer();
        upload.dispose();
    }                                         

    private void picScrFieldMouseClicked(java.awt.event.MouseEvent evt) {                                         
        // TODO add your handling code here:
        if(availableProjectsModel.getSize() != 0){ 
        upload.setVisible(true);
        }
    }                                        

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void writeJSONBtnActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
        writeJSONconfirm.dispose();
    }
    private void cancelWriteBtnActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
        writeJSONconfirm.dispose();
    }    
     private void writeJSONMainBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_writeJSONMainBtnActionPerformed
        // TODO add your handling code here:
         writeJSONconfirm.setVisible(true);
    }//GEN-LAST:event_writeJSONMainBtnActionPerformed
       
    private void giveProjectNameCancelActionPerformed(java.awt.event.ActionEvent evt) {                                                      
        // TODO add your handling code here:
        giveProjectName.dispose();
    }                                                     

    private void giveProjectNameOKActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        // TODO add your handling code here:
        Project newProj = new Project(this.newProjectNameField.getText());
        mainComponents.newProject(newProj);
        this.availableProjectsModel.addElement(newProj.getName());
        this.availableProjects.setSelectedIndex(mainComponents.getProjectAmount()-1);
        mainComponents.setActiveProject(mainComponents.getProjectAmount()-1);
        mainComponents.changeProject(availableProjects.getSelectedIndex(),drawArea,availableFilesModel);
        giveProjectName.dispose();
        drawArea.setImg(null);
        mainComponents.setActiveFile(-1);
        updateRenamer();
        repaint();
    }
    private void updateRenamer(){
        if(availableFilesModel.getSize() != 0){
            picScrField.setText(mainComponents.getActualActiveFile().getShapeName());
            givenRefName.setText(mainComponents.getActualActiveFile().getShapeName());
        } else {
            picScrField.setText("no files..");
            givenRefName.setText("no files..");
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);             
            }
        });
         //tästä alaspäin on demoa
        
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton JSONPathBtn;
    private javax.swing.JButton cancelWriteBtn;
    private javax.swing.JTextField givenRefName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel mainTitle;
    private javax.swing.JButton newProject;
    private javax.swing.JButton openProject;
    private javax.swing.JTextField picScrField;
    private javax.swing.JButton refDialCancel;
    private javax.swing.JButton refDialOK;
    private javax.swing.JButton save;
    private javax.swing.JButton settigns;
    private javax.swing.JDialog upload;
    private javax.swing.JButton uploadBtn;
    private javax.swing.JPanel upperNavi;
    private javax.swing.JButton writeJSONBtn;
    private javax.swing.JDialog writeJSONconfirm;
    private javax.swing.JList availableFiles;
    private javax.swing.DefaultListModel availableFilesModel;
    private MouseListener availableFilesListener;
    private javax.swing.JList availableProjects;
    private javax.swing.DefaultListModel availableProjectsModel;
    private MouseListener availableProjectsListener;
    private DrawArea drawArea;
    private javax.swing.JLabel filesLabel;
    private javax.swing.JButton writeJSONMainBtn;
    private javax.swing.JScrollPane filesPanel;
    private javax.swing.JScrollPane projectsPanel;
    private javax.swing.JToggleButton drawTool;
    private javax.swing.JToggleButton deletePointTool;
    private javax.swing.JPanel leftNavi;
    private javax.swing.JLabel projectsLabel;
    private javax.swing.JTextField newProjectNameField;
    private javax.swing.JLabel newProjectNameTitle;
    private javax.swing.JLabel NewProjectNameLabel1;
    private javax.swing.JDialog giveProjectName;
    private javax.swing.JButton giveProjectNameCancel;
    private javax.swing.JButton giveProjectNameOK;
    private javax.swing.JSeparator jSeparator3;
    //variables that main can ask from GUI
    private MainComponents mainComponents;
    // End of variables declaration                   
}
